---
title: "R Notebook"
output: html_notebook
---

```{r}
dataset = read.csv("creditset.csv");

head(dataset)
```

```{r}
trainset = dataset[1:1200,]
testset = dataset[1201:2000,]

if(nrow(trainset) + nrow(testset) != nrow(dataset)){
  print("Error occured while dividing dataset")
  stop();
}

str(dataset)
```
```{r}
library(neuralnet)

model <- model.matrix(~default10yr + income + age + loan + LTI, data = trainset)
head(model)
```
```{r}
NNet = neuralnet(default10yr ~ age + LTI, model, hidden = 4, linear.output = F, lifesign = "minimal", threshold = 0.1)

plot(NNet)
```

```{r}
testSet_Features = subset(testset,select=c("age", "LTI"));

head(testSet_Features)

```
```{r}
NNresults = compute(NNet , testSet_Features );

finalOutput = data.frame(Actual = testset$default10yr,
                          Prediction = NNresults$net.result,
                          Matches = doesPredictionMatch( testset$default10yr, NNresults$net.result, 0.3));

row.names(finalOutput) = NULL;

print(cat("Prediction Success Rate : ",countSuccessPercent(finalOutput$Matches)));

print(finalOutput)
```

```{r}
doesPredictionMatch = function(expected = Null, predicted = Null, threshold = 0.3){
   if(is.null(expected) || is.null(predicted)){
    print("Necessary arguments missing or null");
    stop();
  }
  
  results = rep(FALSE,length(expected));
  
  for(i in 1:length(expected)){
    if((!is.na(expected[i]))&&(!is.na(predicted[i]))){  
      if(abs(expected[i]-predicted[i])<threshold ){
        results[i] = TRUE;
      }
    }
      
  }
  return (results);
}
```

```{r}
countSuccessPercent = function(input = NULL){
  count= 0;
  for(i in 1:length(input)){
    tmp =as.logical(input[i]); 
    if(is.logical(tmp) && tmp ==TRUE ){
      count=count+1;
    }
  }
  return ((count/length(input))*100);  
}
```


```{r}
set.seed(500)
#library(MASS)
data <- read.csv("creditset.csv")
  #Boston
apply(data,2,function(x) sum(is.na(x)))
```

```{r}
index <- sample(1:nrow(data), round(0.75 * nrow(data)))
train <- data[index,]
test <- data[-index,]
#lm.fit <- glm(medv~.,data=train)
lm.fit <- glm(default10yr~.,data=train)
summary(lm.fit)
pr.lm <- predict(lm.fit,test)
MSE.lm <- sum((pr.lm - test$default10yr) ^2/nrow(test))
```

```{r}
maxs <- apply(data,2,max)
mins <- apply(data,2,min)

scaled <- as.data.frame(scale(data, center = mins, scale = maxs-mins))

train2 <- scaled[index,]
test2 <- scaled[-index,]

n<-names(train2)
f <- as.formula(paste("default10yr~",paste(n[!n %in% "default10yr"],collapse = "+")))
nn <- neuralnet(f, data=train2,hidden = c(4,3),linear.output = T)

plot(nn)
``` 
```{r}
tf = subset(test2,select=c("income", "age","loan", "LTI"));

head(tf)
```



```{r}
tf = subset(test2,select=c("income", "age","loan", "LTI"));
print(tf)

pr.nn <- compute(nn,tf)

pr.nn_ <- pr.nn$net.result*(max(data$default10yr)-min(data$default10yr))+min(data$default10yr)
test.r <- (test2$default10yr)*(max(data$default10yr)-min(data$default10yr))+min(data$default10yr)

MSE.nn <- sum((test.r - pr.nn_)^2)/nrow(test2)

print(paste(MSE.lm,MSE.nn))

finalOutput = data.frame(Actual = test2$medv,
                      Prediction = pr.nn$net.result,
                Matches = doesPredictionMatch(test2$medv, pr.nn$net.result, 0.3));

row.names(finalOutput) = NULL;

print(cat("Prediction Success Rate : ",countSuccessPercent(finalOutput$Matches)));

print(finalOutput)
```

```{r}
par(mfrow=c(1,2))

plot(test$medv,pr.nn_,col='red',main='Real vs predicted NN',pch=18,cex=0.7)
abline(0,1,lwd=2)
legend('bottomright',legend='NN',pch=18,col='red', bty='n')

plot(test$medv,pr.lm,col='blue',main='Real vs predicted lm',pch=18, cex=0.7)
abline(0,1,lwd=2)
legend('bottomright',legend='LM',pch=18,col='blue', bty='n', cex=.95)
```
```{r}
print(test2[,2:5])
```

