---
title: "R Notebook"
output: html_notebook
---


```{r}
dataset = read.csv("dataset.csv")

head(dataset)
```

```{r}
numTrain = 0.6 *nrow(dataset)
trainset = dataset[1:numTrain,]
testset = dataset[(numTrain+1):nrow(dataset),]

if(nrow(trainset) + nrow(testset) != nrow(dataset)){
  print("There was an error while dividing dataset")
  stop();
}
```

```{r}
library(neuralnet)
NNet = neuralnet(Default~ LoanBalance + Age, trainset, hidden = 4, linear.output = F,lifesign = "minimal", threshold = 0.1)

plot(NNet)
```

```{r}
run = function(percentTrain = 0.5, roundOff = T, outputClosenessThreshold = 0.3, HLNodes = 4) {
                                                  }
  
   NNet =  neuralnet(default~ LoanToValue + Age + Income + LoanBalance +                                  InterestRate + MortgageYears+ PropertyValue + AnnualPayment
                     + CreditRating, trainSet, 
                     hidden = HLNodes ,linear.output=F,
                     lifesign="minimal",threshold = 0.1);
   plot(NNet);
   
   testSet_Features =   subset(testSet, select = c("LoanToValue", "Age", "Income",                         "LoanBalance", "InterestRate", "MortgageYears",                                    "PropertyValue", "AnnualPayment",  "CreditRating"));
   
    NNresults = compute(NNet , testSet_Features );
    if(roundOff){
                  NNresults$net.result = round(NNresults$net.result);
                }
   
   finalOutput = data.frame(Actual = testSet$default,
                          Prediction = NNresults$net.result,
                          Matches = doesPredictionMatch(testSet$default,                                            NNresults$net.result, outputClosenessThreshold));
   row.names(finalOutput) = NULL;
   
   print(cat("Prediction Success Rate : ",                   countSuccessPercent(finalOutput$Matches)));
  
  return(finalOutput);
}
doesPredictionMatch = function( expected =NULL , predicted = NULL , threshold = 0.3){
  if(is.null(expected) || is.null(predicted)){
    print("Necessary arguments missing or null");
    stop();
  }
  
  results = rep(FALSE,length(expected));
  
  for(i in 1:length(expected)){
    if((!is.na(expected[i]))&&(!is.na(predicted[i]))){  
      if(abs(expected[i]-predicted[i])<threshold ){
        results[i] = TRUE;
      }
    }
      
  }
  return (results);
}

countSuccessPercent = function(input = NULL){
  count= 0;
  for(i in 1:length(input)){
    tmp =as.logical(input[i]); 
    if(is.logical(tmp) && tmp ==TRUE ){
      count=count+1;
    }
  }
  return ((count/length(input))*100);  
}
```

