---
title: "R Notebook"
output: html_notebook
---


```{r}
set.seed(1234)

mydata <- read.csv("dataset.csv")
apply(mydata,2,function(x) sum(is.na(x)))

#str(mydata)

df <- mydata[c(2,4:6,11:14)] 
```
```{r}
index <- sample(1:nrow(df), round(0.7*nrow(df)))
train <- df[index,]
test <- df[-index,]
#train <- mydata[1:2000,]
#test <- mydata[2001:2500,]
lm.fit <- glm(Default~.,data=train)
summary(lm.fit)
pr.lm <- predict(lm.fit,test)
MSE.lm <- sum((pr.lm - test$Default) ^2/nrow(test))
```
```{r}
library(neuralnet)
maxs <- apply(df,2,max)
mins <- apply(df,2,min)

scaled <- as.data.frame(scale(df, center = mins, scale = maxs-mins))

train2 <- scaled[index,]
test2 <- scaled[-index,]

n<-names(train2)
f <- as.formula(paste("Default~",paste(n[!n %in% "Default"],collapse = "+")))
nn <- neuralnet(f, data=train2,hidden = 7,linear.output = F,stepmax = 1000000)

plot(nn)
```
```{r}
testSet_Features = subset(testset,select=c("Income", "Age","InterestType","MortgageType","CreditRating","InterestRate","LoanToValue"));

head(testSet_Features)
```

```{r}

NNresults = compute(nn,testSet_Features );
print(nrow(NNresults$net.result),nrow(test2$Default))
finalOutput = data.frame(Actual = test2$Default,
                          Prediction = NNresults$net.result,
                          Matches = doesPredictionMatch(test2$Default, NNresults$net.result, 0.3));

```
```{r}
doesPredictionMatch = function(expected = Null, predicted = Null, threshold = 0.3){
   if(is.null(expected) || is.null(predicted)){
    print("Necessary arguments missing or null");
    stop();
  }
  
  results = rep(FALSE,length(expected));
  
  for(i in 1:length(expected)){
    if((!is.na(expected[i]))&&(!is.na(predicted[i]))){  
      if(abs(expected[i]-predicted[i])<threshold ){
        results[i] = TRUE;
      }
    }
      
  }
  return (results);
}
countSuccessPercent = function(input = NULL){
  count= 0;
  for(i in 1:length(input)){
    tmp =as.logical(input[i]); 
    if(is.logical(tmp) && tmp ==TRUE ){
      count=count+1;
    }
  }
  return ((count/length(input))*100);  
}
```

```{r}


pr.nn <- compute(nn,test2[,1:7])
pr.nn_ <- pr.nn$net.result*(max(df$Default)-min(df$Default))+min(df$Default)
test.r <- (test2$Default)*(max(df$Default)-min(df$Default))+min(df$Default)

MSE.nn <- sum((test.r - pr.nn_)^2)/nrow(test2)

print(paste(MSE.lm,MSE.nn))
```

```{r}
par(mfrow=c(1,2))

plot(test2$Default,pr.nn_,col='red',main='Real vs predicted NN',pch=18,cex=0.7)
abline(0,1,lwd=2)
legend('bottomright',legend='NN',pch=18,col='red', bty='n')

plot(test$Default,pr.lm,col='blue',main='Real vs predicted lm',pch=18, cex=0.7)
abline(0,1,lwd=2)
legend('bottomright',legend='LM',pch=18,col='blue', bty='n', cex=.95)
```
```{r}
plot(test$Default,pr.nn_,col='red',main='Real vs predicted NN',pch=18,cex=0.7)
points(test$Default,pr.lm,col='blue',pch=18,cex=0.7)
abline(0,1,lwd=2)
legend('bottomright',legend=c('NN','LM'),pch=18,col=c('red','blue'))
```

